name: Project_pep_block
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyarrow
  - biopython
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - scikit-learn
  - pip:
    - python-dotenv
    - -e .